packages:
  - 'server'
  - 'sdk'
  - 'plugins/*'
  - '!plugins/cloud'
  - 'frontend'
  - 'packages/*'

dangerouslyAllowAllBuilds: true

minimumReleaseAgeExclude:
  - '@typescript/typescript-aix-ppc64@7.0.2'
  - '@typescript/typescript-darwin-arm64@7.0.2'
  - '@typescript/typescript-darwin-x64@7.0.2'
  - '@typescript/typescript-freebsd-arm64@7.0.2'
  - '@typescript/typescript-freebsd-x64@7.0.2'
  - '@typescript/typescript-linux-arm64@7.0.2'
  - '@typescript/typescript-linux-arm@7.0.2'
  - '@typescript/typescript-linux-loong64@7.0.2'
  - '@typescript/typescript-linux-mips64el@7.0.2'
  - '@typescript/typescript-linux-ppc64@7.0.2'
  - '@typescript/typescript-linux-riscv64@7.0.2'
  - '@typescript/typescript-linux-s390x@7.0.2'
  - '@typescript/typescript-linux-x64@7.0.2'
  - '@typescript/typescript-netbsd-arm64@7.0.2'
  - '@typescript/typescript-netbsd-x64@7.0.2'
  - '@typescript/typescript-openbsd-arm64@7.0.2'
  - '@typescript/typescript-openbsd-x64@7.0.2'
  - '@typescript/typescript-sunos-x64@7.0.2'
  - '@typescript/typescript-win32-arm64@7.0.2'
  - '@typescript/typescript-win32-x64@7.0.2'
  - typescript@7.0.2
  - '@matterbridge/core@3.9.4'
  - '@matterbridge/dgram@3.9.4'
  - '@matterbridge/jest-utils@3.9.4'
  - '@matterbridge/thread@3.9.4'
  - '@matterbridge/types@3.9.4'
  - '@matterbridge/utils@3.9.4'
  - '@matterbridge/vitest-utils@3.9.4'
  - matterbridge@3.9.4
