name: "Scryvex Pro"
version: "3.0.0-alpha.9"
slug: "scryvex_pro_final"
description: "Plataforma universal de administración para Scrypted — versión alfa"
url: "https://github.com/Chrisalvir1/Scryvex-Pro-V2"
image: ghcr.io/chrisalvir1/scryvex-pro-v2
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 19090
panel_icon: mdi:cctv
hassio_api: true
homeassistant_api: true
host_network: true
options: {}
schema: {}
